version: '3'

networks:
  user-local-network:
    driver: bridge
    name: user-local-network

services:

  user-clientes-mysql:
     image: mysql:5.7
     container_name: user-clientes-mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: userclientes
       MYSQL_USER: user
       MYSQL_PASSWORD: user
     ports:
       - 3306:3306
     networks:
       - user-local-network
     volumes:
       - .:/usr/src/app
